/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.datastream.khodza.model.avro.p_presentronik_cache_kelas_sesi_perkuliahan_mahasiswa_peserta;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Value extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7670774712366182958L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Value\",\"namespace\":\"org.datastream.khodza.model.avro.p_presentronik_cache_kelas_sesi_perkuliahan_mahasiswa_peserta\",\"fields\":[{\"name\":\"id_kuliah\",\"type\":\"long\"},{\"name\":\"npm\",\"type\":\"string\"},{\"name\":\"kd_org\",\"type\":\"string\"},{\"name\":\"ts_update\",\"type\":{\"type\":\"long\",\"connect.version\":1,\"connect.name\":\"io.debezium.time.MicroTimestamp\"}},{\"name\":\"status_presensi\",\"type\":\"int\"},{\"name\":\"ts_last_sync_with_siak\",\"type\":[\"null\",{\"type\":\"long\",\"connect.version\":1,\"connect.name\":\"io.debezium.time.MicroTimestamp\"}],\"default\":null},{\"name\":\"nama_mahasiswa\",\"type\":[\"null\",\"string\"],\"default\":null}],\"connect.name\":\"p_presentronik.presentronik.cache_kelas_sesi_perkuliahan_mahasiswa_peserta.Value\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long id_kuliah;
  @Deprecated public java.lang.CharSequence npm;
  @Deprecated public java.lang.CharSequence kd_org;
  @Deprecated public long ts_update;
  @Deprecated public int status_presensi;
  @Deprecated public java.lang.Long ts_last_sync_with_siak;
  @Deprecated public java.lang.CharSequence nama_mahasiswa;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Value() {}

  /**
   * All-args constructor.
   * @param id_kuliah The new value for id_kuliah
   * @param npm The new value for npm
   * @param kd_org The new value for kd_org
   * @param ts_update The new value for ts_update
   * @param status_presensi The new value for status_presensi
   * @param ts_last_sync_with_siak The new value for ts_last_sync_with_siak
   * @param nama_mahasiswa The new value for nama_mahasiswa
   */
  public Value(java.lang.Long id_kuliah, java.lang.CharSequence npm, java.lang.CharSequence kd_org, java.lang.Long ts_update, java.lang.Integer status_presensi, java.lang.Long ts_last_sync_with_siak, java.lang.CharSequence nama_mahasiswa) {
    this.id_kuliah = id_kuliah;
    this.npm = npm;
    this.kd_org = kd_org;
    this.ts_update = ts_update;
    this.status_presensi = status_presensi;
    this.ts_last_sync_with_siak = ts_last_sync_with_siak;
    this.nama_mahasiswa = nama_mahasiswa;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id_kuliah;
    case 1: return npm;
    case 2: return kd_org;
    case 3: return ts_update;
    case 4: return status_presensi;
    case 5: return ts_last_sync_with_siak;
    case 6: return nama_mahasiswa;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id_kuliah = (java.lang.Long)value$; break;
    case 1: npm = (java.lang.CharSequence)value$; break;
    case 2: kd_org = (java.lang.CharSequence)value$; break;
    case 3: ts_update = (java.lang.Long)value$; break;
    case 4: status_presensi = (java.lang.Integer)value$; break;
    case 5: ts_last_sync_with_siak = (java.lang.Long)value$; break;
    case 6: nama_mahasiswa = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id_kuliah' field.
   * @return The value of the 'id_kuliah' field.
   */
  public java.lang.Long getIdKuliah() {
    return id_kuliah;
  }

  /**
   * Sets the value of the 'id_kuliah' field.
   * @param value the value to set.
   */
  public void setIdKuliah(java.lang.Long value) {
    this.id_kuliah = value;
  }

  /**
   * Gets the value of the 'npm' field.
   * @return The value of the 'npm' field.
   */
  public java.lang.CharSequence getNpm() {
    return npm;
  }

  /**
   * Sets the value of the 'npm' field.
   * @param value the value to set.
   */
  public void setNpm(java.lang.CharSequence value) {
    this.npm = value;
  }

  /**
   * Gets the value of the 'kd_org' field.
   * @return The value of the 'kd_org' field.
   */
  public java.lang.CharSequence getKdOrg() {
    return kd_org;
  }

  /**
   * Sets the value of the 'kd_org' field.
   * @param value the value to set.
   */
  public void setKdOrg(java.lang.CharSequence value) {
    this.kd_org = value;
  }

  /**
   * Gets the value of the 'ts_update' field.
   * @return The value of the 'ts_update' field.
   */
  public java.lang.Long getTsUpdate() {
    return ts_update;
  }

  /**
   * Sets the value of the 'ts_update' field.
   * @param value the value to set.
   */
  public void setTsUpdate(java.lang.Long value) {
    this.ts_update = value;
  }

  /**
   * Gets the value of the 'status_presensi' field.
   * @return The value of the 'status_presensi' field.
   */
  public java.lang.Integer getStatusPresensi() {
    return status_presensi;
  }

  /**
   * Sets the value of the 'status_presensi' field.
   * @param value the value to set.
   */
  public void setStatusPresensi(java.lang.Integer value) {
    this.status_presensi = value;
  }

  /**
   * Gets the value of the 'ts_last_sync_with_siak' field.
   * @return The value of the 'ts_last_sync_with_siak' field.
   */
  public java.lang.Long getTsLastSyncWithSiak() {
    return ts_last_sync_with_siak;
  }

  /**
   * Sets the value of the 'ts_last_sync_with_siak' field.
   * @param value the value to set.
   */
  public void setTsLastSyncWithSiak(java.lang.Long value) {
    this.ts_last_sync_with_siak = value;
  }

  /**
   * Gets the value of the 'nama_mahasiswa' field.
   * @return The value of the 'nama_mahasiswa' field.
   */
  public java.lang.CharSequence getNamaMahasiswa() {
    return nama_mahasiswa;
  }

  /**
   * Sets the value of the 'nama_mahasiswa' field.
   * @param value the value to set.
   */
  public void setNamaMahasiswa(java.lang.CharSequence value) {
    this.nama_mahasiswa = value;
  }

  /**
   * Creates a new Value RecordBuilder.
   * @return A new Value RecordBuilder
   */
  public static Value.Builder newBuilder() {
    return new Value.Builder();
  }

  /**
   * Creates a new Value RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Value RecordBuilder
   */
  public static Value.Builder newBuilder(Value.Builder other) {
    return new Value.Builder(other);
  }

  /**
   * Creates a new Value RecordBuilder by copying an existing Value instance.
   * @param other The existing instance to copy.
   * @return A new Value RecordBuilder
   */
  public static Value.Builder newBuilder(Value other) {
    return new Value.Builder(other);
  }

  /**
   * RecordBuilder for Value instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Value>
    implements org.apache.avro.data.RecordBuilder<Value> {

    private long id_kuliah;
    private java.lang.CharSequence npm;
    private java.lang.CharSequence kd_org;
    private long ts_update;
    private int status_presensi;
    private java.lang.Long ts_last_sync_with_siak;
    private java.lang.CharSequence nama_mahasiswa;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Value.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id_kuliah)) {
        this.id_kuliah = data().deepCopy(fields()[0].schema(), other.id_kuliah);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.npm)) {
        this.npm = data().deepCopy(fields()[1].schema(), other.npm);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.kd_org)) {
        this.kd_org = data().deepCopy(fields()[2].schema(), other.kd_org);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ts_update)) {
        this.ts_update = data().deepCopy(fields()[3].schema(), other.ts_update);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.status_presensi)) {
        this.status_presensi = data().deepCopy(fields()[4].schema(), other.status_presensi);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.ts_last_sync_with_siak)) {
        this.ts_last_sync_with_siak = data().deepCopy(fields()[5].schema(), other.ts_last_sync_with_siak);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.nama_mahasiswa)) {
        this.nama_mahasiswa = data().deepCopy(fields()[6].schema(), other.nama_mahasiswa);
        fieldSetFlags()[6] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Value instance
     * @param other The existing instance to copy.
     */
    private Builder(Value other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id_kuliah)) {
        this.id_kuliah = data().deepCopy(fields()[0].schema(), other.id_kuliah);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.npm)) {
        this.npm = data().deepCopy(fields()[1].schema(), other.npm);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.kd_org)) {
        this.kd_org = data().deepCopy(fields()[2].schema(), other.kd_org);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ts_update)) {
        this.ts_update = data().deepCopy(fields()[3].schema(), other.ts_update);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.status_presensi)) {
        this.status_presensi = data().deepCopy(fields()[4].schema(), other.status_presensi);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.ts_last_sync_with_siak)) {
        this.ts_last_sync_with_siak = data().deepCopy(fields()[5].schema(), other.ts_last_sync_with_siak);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.nama_mahasiswa)) {
        this.nama_mahasiswa = data().deepCopy(fields()[6].schema(), other.nama_mahasiswa);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'id_kuliah' field.
      * @return The value.
      */
    public java.lang.Long getIdKuliah() {
      return id_kuliah;
    }

    /**
      * Sets the value of the 'id_kuliah' field.
      * @param value The value of 'id_kuliah'.
      * @return This builder.
      */
    public Value.Builder setIdKuliah(long value) {
      validate(fields()[0], value);
      this.id_kuliah = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id_kuliah' field has been set.
      * @return True if the 'id_kuliah' field has been set, false otherwise.
      */
    public boolean hasIdKuliah() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id_kuliah' field.
      * @return This builder.
      */
    public Value.Builder clearIdKuliah() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'npm' field.
      * @return The value.
      */
    public java.lang.CharSequence getNpm() {
      return npm;
    }

    /**
      * Sets the value of the 'npm' field.
      * @param value The value of 'npm'.
      * @return This builder.
      */
    public Value.Builder setNpm(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.npm = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'npm' field has been set.
      * @return True if the 'npm' field has been set, false otherwise.
      */
    public boolean hasNpm() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'npm' field.
      * @return This builder.
      */
    public Value.Builder clearNpm() {
      npm = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'kd_org' field.
      * @return The value.
      */
    public java.lang.CharSequence getKdOrg() {
      return kd_org;
    }

    /**
      * Sets the value of the 'kd_org' field.
      * @param value The value of 'kd_org'.
      * @return This builder.
      */
    public Value.Builder setKdOrg(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.kd_org = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'kd_org' field has been set.
      * @return True if the 'kd_org' field has been set, false otherwise.
      */
    public boolean hasKdOrg() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'kd_org' field.
      * @return This builder.
      */
    public Value.Builder clearKdOrg() {
      kd_org = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'ts_update' field.
      * @return The value.
      */
    public java.lang.Long getTsUpdate() {
      return ts_update;
    }

    /**
      * Sets the value of the 'ts_update' field.
      * @param value The value of 'ts_update'.
      * @return This builder.
      */
    public Value.Builder setTsUpdate(long value) {
      validate(fields()[3], value);
      this.ts_update = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'ts_update' field has been set.
      * @return True if the 'ts_update' field has been set, false otherwise.
      */
    public boolean hasTsUpdate() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'ts_update' field.
      * @return This builder.
      */
    public Value.Builder clearTsUpdate() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'status_presensi' field.
      * @return The value.
      */
    public java.lang.Integer getStatusPresensi() {
      return status_presensi;
    }

    /**
      * Sets the value of the 'status_presensi' field.
      * @param value The value of 'status_presensi'.
      * @return This builder.
      */
    public Value.Builder setStatusPresensi(int value) {
      validate(fields()[4], value);
      this.status_presensi = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'status_presensi' field has been set.
      * @return True if the 'status_presensi' field has been set, false otherwise.
      */
    public boolean hasStatusPresensi() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'status_presensi' field.
      * @return This builder.
      */
    public Value.Builder clearStatusPresensi() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'ts_last_sync_with_siak' field.
      * @return The value.
      */
    public java.lang.Long getTsLastSyncWithSiak() {
      return ts_last_sync_with_siak;
    }

    /**
      * Sets the value of the 'ts_last_sync_with_siak' field.
      * @param value The value of 'ts_last_sync_with_siak'.
      * @return This builder.
      */
    public Value.Builder setTsLastSyncWithSiak(java.lang.Long value) {
      validate(fields()[5], value);
      this.ts_last_sync_with_siak = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'ts_last_sync_with_siak' field has been set.
      * @return True if the 'ts_last_sync_with_siak' field has been set, false otherwise.
      */
    public boolean hasTsLastSyncWithSiak() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'ts_last_sync_with_siak' field.
      * @return This builder.
      */
    public Value.Builder clearTsLastSyncWithSiak() {
      ts_last_sync_with_siak = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'nama_mahasiswa' field.
      * @return The value.
      */
    public java.lang.CharSequence getNamaMahasiswa() {
      return nama_mahasiswa;
    }

    /**
      * Sets the value of the 'nama_mahasiswa' field.
      * @param value The value of 'nama_mahasiswa'.
      * @return This builder.
      */
    public Value.Builder setNamaMahasiswa(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.nama_mahasiswa = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'nama_mahasiswa' field has been set.
      * @return True if the 'nama_mahasiswa' field has been set, false otherwise.
      */
    public boolean hasNamaMahasiswa() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'nama_mahasiswa' field.
      * @return This builder.
      */
    public Value.Builder clearNamaMahasiswa() {
      nama_mahasiswa = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    public Value build() {
      try {
        Value record = new Value();
        record.id_kuliah = fieldSetFlags()[0] ? this.id_kuliah : (java.lang.Long) defaultValue(fields()[0]);
        record.npm = fieldSetFlags()[1] ? this.npm : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.kd_org = fieldSetFlags()[2] ? this.kd_org : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.ts_update = fieldSetFlags()[3] ? this.ts_update : (java.lang.Long) defaultValue(fields()[3]);
        record.status_presensi = fieldSetFlags()[4] ? this.status_presensi : (java.lang.Integer) defaultValue(fields()[4]);
        record.ts_last_sync_with_siak = fieldSetFlags()[5] ? this.ts_last_sync_with_siak : (java.lang.Long) defaultValue(fields()[5]);
        record.nama_mahasiswa = fieldSetFlags()[6] ? this.nama_mahasiswa : (java.lang.CharSequence) defaultValue(fields()[6]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
